### ISSUE TITLE
mysql 文字コード格闘メモ

### ISSUE THREAD

**Issue by takunoko** [takunoko/GH_Actions-Test#2]
## 問題
GitHub Actionsのserviceからmysqlを起動するとcharsetがlatin1になってしまう
![image](https://user-images.githubusercontent.com/2417269/147911818-d3ed967d-6835-4ef1-a123-a29d46f329ac.png)

この状態だと、日本語のインポートでコケる。
(たぶん)これをutf8にすることで日本語のインポートこけなくなるので、なんとかしたい

**Comment by takunoko** [comment]
## だめなパターン
```
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db
          MYSQL_USER: db_user
          MYSQL_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        options: --health-cmd "mysqladmin ping -hlocalhost" --health-interval 10s --health-timeout 10s --health-retries 10
```
